### ISSUE TITLE
Feature Request: URL encode data

### ISSUE THREAD

**Issue by hydrian** [chao/RESTClient#32]
Add option (checkbox in UI) to URL encode JSON data before submitting http request.

**Comment by nucc1** [comment]
If you need to specify an Odata filter, you will need to include spaces in your query. At the moment, you cannot submit the request because this extension doesn't like spaces in the URL

**Comment by nucc1** [comment]
See https://msdn.microsoft.com/en-us/library/hh169248(v=nav.90).aspx for Odata filter example.

**Comment by foo123** [comment]
Hello I use restclient to test an HTTP JSON API server (http://jsonapi.org/format/). I use GET,POST,PATCH and DELETE. I send json data in the request body. Are these encoded on send or do I need to encode them myself manualy? I dont understand and there is no option for this. I am in need of this test so to test the server. Any help in this direction is greatly appreciated. What do I have to do in order to post or patch request body containing json data?

Thanks,
Nikos
